package io.github.protasm.lpc2j.scanner;

public enum TokenType {
    TOKEN_BANG, TOKEN_BANG_EQUAL, TOKEN_COLON, TOKEN_COMMA, TOKEN_DBL_AMP, TOKEN_DBL_PIPE, TOKEN_DOT, TOKEN_ELSE,
    TOKEN_EOF, TOKEN_EQUAL, TOKEN_EQUAL_EQUAL, TOKEN_ERROR, TOKEN_FALSE, TOKEN_FOR, TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_IDENTIFIER, TOKEN_IF, TOKEN_INHERIT, TOKEN_INVOKE, TOKEN_LEFT_BRACE, TOKEN_LEFT_BRACKET, TOKEN_LEFT_PAREN,
    TOKEN_LESS, TOKEN_LESS_EQUAL, TOKEN_MINUS, TOKEN_MINUS_EQUAL, TOKEN_MINUS_MINUS, TOKEN_NIL, TOKEN_NUM_FLOAT,
    TOKEN_NUM_INT, TOKEN_PLUS, TOKEN_PLUS_EQUAL, TOKEN_PLUS_PLUS, TOKEN_RETURN, TOKEN_RIGHT_BRACE, TOKEN_RIGHT_BRACKET,
    TOKEN_RIGHT_PAREN, TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_SLASH_EQUAL, TOKEN_STAR, TOKEN_STAR_EQUAL, TOKEN_STRING,
    TOKEN_SUPER, TOKEN_TRUE, TOKEN_TYPE, TOKEN_WHILE
}
