/**
 * Lightweight runtime helpers consumed by generated bytecode.
 *
 * <p>Currently provides truthiness utilities aligned with LPC semantics for use by compiled control
 * flow. Methods are static and side-effect free to keep emitted code simple.</p>
 *
 * <p>This layer is intentionally minimal; broader game-engine services or object models are expected
 * to live elsewhere.</p>
 */
package io.github.protasm.lpc2j.runtime;
