/**
 * Interfaces and registry for LPC efuns (built-in functions).
 *
 * <p>Defines the {@link io.github.protasm.lpc2j.efun.Efun} contract and a simple {@link
 * io.github.protasm.lpc2j.efun.EfunRegistry} for lookups at runtime. Efuns provide names, arity, and
 * invocation behavior used by generated bytecode.</p>
 *
 * <p>Assumes concrete implementations are supplied elsewhere (e.g., console efuns) and that callers
 * register them before compiled code executes. Registry lookups are unchecked beyond name presence.</p>
 */
package io.github.protasm.lpc2j.efun;
